config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'orders#new'

  namespace :admin do
    resources :orders
    resources :items
  end

  resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, :unit_quantity, :unit_cost, presence: true
  has_many :order_items
  has_many :orders, through: :order_items
end

app/models/order.rb
class Order < ApplicationRecord
  validates :name, :address, :phone, presence: true
  has_many :order_items
  has_many :items, through: :order_items
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < AdminController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "Item saved successfully."
      redirect_to admin_items_path
    else
      flash[:notice] = "Item could not be saved."
      render :new
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :description, :unit_quantity, :unit_cost, :available)
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController

  def index
    @orders = Order.all.includes(:items)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end

  def after_sign_in_path_for(resource)
    if current_user.admin?
      admin_orders_path
    else
      super
    end
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    byebug
    if @order.save
      flash[:notice] = "Order saved successfully."
      redirect_to admin_orders_path
    else
      flash[:notice] = "Order could not be saved."
      render :new
    end
  end

  private
  def order_params
    params.require(:order).permit(:name, :company, :address, :phone, :needed_by, item_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/items/index.haml
.row
  .col-sm-12
    %h1 All Items
    %p= link_to "New Item", new_admin_item_path, class: "btn btn-primary"

.row
  .col-sm-12
    %table.table
      %thead
        %tr
          %th Name
          %th Description
          %th Unit Quantity
          %th Unit Cost
          %th Available?
      %tbody
        - @items.each do |item|
          %tr
            %td= item.name
            %td= item.description
            %td= item.unit_quantity
            %td= item.unit_cost
            %td= item.available

app/views/admin/items/new.haml
.row
  .col-sm-12
    %h1 New Item

.row
  .col-sm-12
    = simple_form_for [:admin, @item] do |f|
      = f.input :name
      = f.input :description
      = f.input :unit_quantity
      = f.input :unit_cost, label: "Unit Cost: $"
      = f.input :available
      = f.submit

app/views/admin/orders/index.haml
.row
  .col-sm-12
    %h1 All Orders
    %p= link_to "New Order", new_order_path, class: "btn btn-primary"

.row
  .col-sm-12
    %table.table
      %thead
        %tr
          %th Name
          %th Company
          %th Address
          %th Phone
          %th Items
      %tbody
        - @orders.each do |order|
          %tr
            %td= order.user.name
            %td= order.user.company
            %td= order.user.address
            %td= order.user.phone
            %td= order.items.map(&:name).join(", ")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Dadsite
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    -if flash[:notice]
      %p= flash[:notice]

    = yield

app/views/layouts/devise.haml
!!!
%html
  %head
    %title Dadsite
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    -if flash[:notice]
      %p= flash[:notice]

    .container
      .row
        .col-sm-3
        .col-sm-8
          .devise-container
            = yield

app/views/orders/new.haml
.row
  .col-sm-6
    .h1 Welcome
  .col-sm-6
    .h2 Buy Something

.row
  .col-sm-12
    = simple_form_for @order do |f|
      = f.association :items, collection: Item.all
      = f.input :needed_by
      = f.submit "Submit Order", class: "btn btn-primary"